services:

  client:
    image: nginx:alpine
    container_name: auction-client
    ports:
      - "80:80"
    volumes:
      - ./frontend-client/dist:/usr/share/nginx/html

  admin:
    image: nginx:alpine
    container_name: auction-admin
    ports:
      - "8080:80"
    volumes:
      - ./frontend-admin/dist:/usr/share/nginx/html
  mysql:
    image: mysql:8.0.42
    container_name: auction-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: live_auction
      MYSQL_USER: auction
      MYSQL_PASSWORD: auction123
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: auction-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    container_name: auction-backend
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: live_auction
      REDIS_URL: redis://redis:6379
      PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

volumes:
  mysql-data:
  redis-data: